// Run with: bun src/_gen_onepiece_thumbs.ts
// Generates onepieceThumbs.ts with base64 PNG thumbnails for each variant.
import { createCanvas } from "canvas";
import { drawOnePieceCell, ONEPIECE_VARIANTS } from "./lib/onepiece";

const SIZE = 64;
const lines: string[] = [
  "// AUTO-GENERATED by _gen_onepiece_thumbs.ts — do not edit by hand.",
  "export const ONEPIECE_THUMBS: Record<string, string> = {",
];

for (const variant of ONEPIECE_VARIANTS) {
  const canvas = createCanvas(SIZE, SIZE);
  const ctx = canvas.getContext("2d");
  ctx.antialias = "none";
  drawOnePieceCell(ctx as never, 0, 0, SIZE, 3, variant, 0);
  const b64 = canvas.toDataURL("image/png");
  lines.push(`  "${variant}": "${b64}",`);
}

lines.push("};");
console.log(lines.join("\n"));
