// Run with: bun src/_gen_aot_thumbs.ts > src/lib/aotThumbs.ts
// Generates aotThumbs.ts with base64 PNG thumbnails for each AoT variant.
import { createCanvas } from "canvas";
import { ATTACKONTITAN_VARIANTS } from "./lib/attackontitan";
import { drawAotThumb } from "./lib/aotScene";

const SIZE = 96;
const lines: string[] = [
  "// AUTO-GENERATED by _gen_aot_thumbs.ts — do not edit by hand.",
  "export const AOT_THUMBS: Record<string, string> = {",
];

for (const variant of ATTACKONTITAN_VARIANTS) {
  const canvas = createCanvas(SIZE, SIZE);
  const ctx = canvas.getContext("2d");
  drawAotThumb(ctx as never, variant, SIZE);
  const b64 = canvas.toDataURL("image/png");
  lines.push(`  "${variant}": "${b64}",`);
}

lines.push("};");
console.log(lines.join("\n"));
